### ISSUE TITLE
ModuleNotFoundError: No module named 'fetch'

### ISSUE THREAD

**Issue by minhazulislam** [snirandjan/CISI#1]
Hi, I tried to develop the environment in my system. I encountered this error: "ModuleNotFoundError: No module named 'fetch'." Basically, it comes with "import cisi_exposure", which could not find the "fetch" library. Please, can you help me on this?

**Comment by snirandjan** [comment]
Dear Minhazul, 

Thank you for pointing this out. The 'fetch' module does not need to be imported. Hence, this line can be deleted. The 'fetch' module contained the code to extract OpenStreetMap data. However, this module had been renamed to 'extract' and is imported in 'cisi_run'. Hope this helps!

Best, 
Sadhana

**Comment by minhazulislam** [comment]
Thank you so much. That worked.
